In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.4.1+cu121


#Introduction to Tensors

###Creating Tensors

In [ ]:
# Scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor

tensor = torch.tensor([[1,2,3],[2,4,5],[5,6,7]])
tensor

tensor([[1, 2, 3],
        [2, 4, 5],
        [5, 6, 7]])

In [ ]:
tensor.ndim

2

In [ ]:
tensor.shape

torch.Size([3, 3])

#Random Tensors

In [ ]:
random_torch = torch.rand(3,4)
random_torch

tensor([[0.7021, 0.3065, 0.8945, 0.3193],
        [0.6983, 0.9111, 0.1486, 0.6006],
        [0.0165, 0.9946, 0.0894, 0.2248]])

In [ ]:
torch.rand(3,3)

tensor([[0.0517, 0.2101, 0.3789],
        [0.1447, 0.2275, 0.6376],
        [0.1503, 0.9361, 0.2690]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32